FROM node:19-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY  . .

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

RUN npm run build 

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

RUN echo 'server{ \
    listen 80; \
    location / { \
    root /usr/share/nginx/html; \
    index index.html index.htm; \
    try_files $uri $uri/ /index.html; \
    } \
    }' > /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
